# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bangazonapi', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('payment_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
