# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bangazonapi', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('billing_address', models.TextField()),
                ('payment_type', models.CharField(max_length=20)),
            ],
        ),
    ]
