# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0003_order'),
        ('bangazonapi', '0003_user'),
    ]

    operations = [
    ]
