# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0003_payment_type'),
        ('bangazonapi', '0005_order_buyer'),
    ]

    operations = [
    ]
