# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0005_auto_20170131_1512'),
        ('bangazonapi', '0004_auto_20170131_2046'),
    ]

    operations = [
    ]
