# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0006_merge_20170303_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=55)),
            ],
            options={
                'ordering': ('category_name',),
            },
        ),
        migrations.RemoveField(
            model_name='payment_type',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment_type',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoryId',
        ),
        migrations.AddField(
            model_name='payment_type',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Customer'),
        ),
        migrations.AddField(
            model_name='payment_type',
            name='payment_name',
            field=models.CharField(default='Unknown Payment Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bangazonapi.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Payment_Type'),
        ),
        migrations.AlterField(
            model_name='payment_type',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment_type',
            name='billing_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment_type',
            name='expiration_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product_on_order',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_on_order', to='bangazonapi.Order'),
        ),
        migrations.AlterField(
            model_name='product_on_order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_on_order', to='bangazonapi.Product'),
        ),
        migrations.DeleteModel(
            name='Product_Category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Product_Type'),
        ),
    ]
