# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0006_merge_20170125_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Payment_Type'),
        ),
        migrations.AddField(
            model_name='payment_type',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.User'),
        ),
    ]
