# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0007_auto_20170125_1207'),
        ('bangazonapi', '0003_products'),
    ]

    operations = [
    ]
