# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0011_auto_20170125_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_on_order',
        ),
    ]
