# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0012_remove_order_product_on_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Category'),
        ),
    ]
