# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0013_product_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_On_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bangazonapi.Product')),
            ],
        ),
    ]
