# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0014_order_product_on_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_on_order',
            field=models.ManyToManyField(to='bangazonapi.Product'),
        ),
    ]
