# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0014_product_on_order'),
        ('bangazonapi', '0015_auto_20170125_2057'),
    ]

    operations = [
    ]
