# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0016_merge_20170126_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_on_order',
        ),
    ]
