# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    '''Migration loads initial seed data for all tables on makemigrations'''

    dependencies = [
        ('bangazonapi', '0014_product_on_order'),
    ]

    operations = [
    ]