# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0018_auto_20170126_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Product_Category',
        ),
    ]
