# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0017_remove_order_product_on_order'),
        ('bangazonapi', '0018_auto_20170126_1608'),
    ]

    operations = [
    ]
