# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0019_merge_20170126_1724'),
        ('bangazonapi', '0020_load_intial_data'),
    ]

    operations = [
    ]
