# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0022_test_data'),
        ('bangazonapi', '0021_merge_20170126_1755'),
    ]

    operations = [
    ]
