# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0024_user_data'),
        ('bangazonapi', '0023_merge_20170126_1822'),
    ]

    operations = [
    ]
